name: Deploy

on:
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY }}
          heroku_app_name: "test-ci-cd-003" #Must be unique in Heroku
          heroku_email: "paulbart171098@gmail.com"